"""empty message

Revision ID: c943f35dc11d
Revises: 9d292789b732
Create Date: 2023-01-15 01:14:17.997095

"""
import os
import random
import datetime as dt
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from project.models import Product, Trip, Place, Truck


# revision identifiers, used by Alembic.
revision = 'c943f35dc11d'
down_revision = '9d292789b732'
branch_labels = None
depends_on = None


def fill_test_data():
    connection = op.get_bind()
    session = Session(bind=connection)

    session.flush()
    available_trucks: list[Truck] = session.query(Truck).all()
    trips: list[Trip] = session.query(Trip).all()

    for trip in trips:
        trip.truck = random.choice(available_trucks)
    session.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('truck_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'trucks', ['truck_id'], ['id'])

    if os.environ.get("MIGRATIONS_WITH_TEST_DATA").upper() == 'TRUE':
        fill_test_data()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('truck_id')

    # ### end Alembic commands ###
