"""empty message

Revision ID: 7dcf82a521ef
Revises: c943f35dc11d
Create Date: 2023-01-20 19:03:12.196091

"""
import os
import random
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from project.models import Product, Trip, Truck


# revision identifiers, used by Alembic.
revision = '7dcf82a521ef'
down_revision = 'c943f35dc11d'
branch_labels = None
depends_on = None


def fill_test_data():
    connection = op.get_bind()
    session = Session(bind=connection)

    session.flush()
    available_products: list[Truck] = session.query(Product).all()
    trips: list[Trip] = session.query(Trip).all()

    for trip in trips:
        for product in random.choices(available_products, k=random.randint(1, 3)):
            trip.products.append(product)
    session.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_product_associations',
                    sa.Column('trip_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], )
                    )
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_constraint('trip_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('product_id')

    if os.environ.get("MIGRATIONS_WITH_TEST_DATA").upper() == 'TRUE':
        fill_test_data()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(
            'trip_product_id_fkey', 'product', ['product_id'], ['id'])

    op.drop_table('trip_product_associations')
    # ### end Alembic commands ###
