"""empty message

Revision ID: bddc4eacdd48
Revises: 8a2f44117898
Create Date: 2023-01-02 22:50:19.202600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from werkzeug.security import generate_password_hash
from project.models import User


# revision identifiers, used by Alembic.
revision = 'bddc4eacdd48'
down_revision = '8a2f44117898'
branch_labels = None
depends_on = None


def create_admin_if_not_exists():
    connection = op.get_bind()
    session = Session(bind=connection)
    query_admin_exists = (session.query(User)
                          .filter(User.name == 'admin')
                          .exists())
    if not session.query(query_admin_exists).scalar():
        admin = User(
            name='admin',
            email='admin@google.com',
            password=generate_password_hash(password='admin',
                                            method='sha256'),
            is_superuser=True
        )
        session.add(admin)
        session.commit()


def delete_admin_if_exist():
    connection = op.get_bind()
    session = Session(bind=connection)
    admin = session.query(User).filter(User.name == 'admin').one_or_none()
    if admin:
        session.delete(admin)
        session.commit()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_superuser', sa.Boolean(), nullable=True)
        )

    connection = op.get_bind()
    session = Session(bind=connection)
    session.execute(sa.update(User).values(is_superuser=False))
    create_admin_if_not_exists()

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_superuser',
                              existing_type=sa.BOOLEAN(),
                              nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_superuser')

    delete_admin_if_exist()

    # ### end Alembic commands ###
